sprint_6: refactoring HistoryManager
rovniipoc/java-kanban pull request #1
Opened 2024-07-07 16:37 UTC by rovniipoc

Добрый день.
Представляю на ревью решение ТЗ 6го спринта.
Спасибо за ревью!

2024-07-08 19:30 UTC, YazykovMikhail requested changes

2024-07-08 19:30 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +    private final CustomLinkedList<Task> historyList = new CustomLinkedList<>();
В задании говорится что делать свою реализацию не нужно, но окей

2024-07-08 19:30 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +    public static class CustomLinkedList<T> {
Есть небольшой рассинхрон, ты делаешь класс через джинерики, но он внутренний, значит что его моугт использовать только внутри класса, т.е только для Task, поэтому можно было просто без дженериков а обьявить в самом классе поле Task data и все.
Либо выносить этот класс из внутреннего класса

2024-07-08 19:30 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +    public static class CustomLinkedList<T> {
Но похорошему, да он должен быть внутренникм как и сами Node ведь они используеются только тут и только для структурирования данных

2024-07-08 19:30 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +        if (historyMap.get(id) == null) {
Вот так будет получше:
```
	public void remove(int id) {
		final Node node = history.remove(id);
		if (node == null) {
			return;
		}
		removeNode(node);
	}
```
Избегай повторных запросов в хранилище

2024-07-08 19:30 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +        if (historyMap.containsKey(taskId)) {
просто вызывай:
remove(taskId)

2024-07-08 19:30 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +        if (historyMap.containsKey(taskId)) {
А то ссылки перестроил, а удалить не удалил

2024-07-09 02:37 UTC, rovniipoc commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +    private final CustomLinkedList<Task> historyList = new CustomLinkedList<>();
Добрый день.
Руководствовался подсказкой из ТЗ:

> Подсказка 2
> Сначала напишите свою реализацию двусвязного списка задач с методами linkLast и getTasks. linkLast будет добавлять задачу в конец этого списка, а getTasks — собирать все задачи из него в обычный ArrayList. Убедитесь, что решение работает. Отдельный класс для списка создавать не нужно — реализуйте его прямо в классе InMemoryHistoryManager. А вот отдельный класс Node для узла списка необходимо добавить.

Если не использовать свою реализацию, то я не понимаю как тогда получать Node из LinkedList (метода возвращающего Node я не нашел...)

2024-07-09 02:43 UTC, rovniipoc commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +    public static class CustomLinkedList<T> {
Сменил дженерик <T> на тип <Task>

P.s. класс был сделан внутренним в соответствии с ТЗ:

> Подсказка 2
> Сначала напишите свою реализацию двусвязного списка задач с методами linkLast и getTasks. linkLast будет добавлять задачу в конец этого списка, а getTasks — собирать все задачи из него в обычный ArrayList. Убедитесь, что решение работает. **Отдельный класс для списка создавать не нужно — реализуйте его прямо в классе InMemoryHistoryManager.** А вот отдельный класс Node для узла списка необходимо добавить.

2024-07-09 02:50 UTC, rovniipoc commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +        if (historyMap.get(id) == null) {
Исправил

2024-07-09 02:58 UTC, rovniipoc commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +        if (historyMap.containsKey(taskId)) {
Исправил.

2024-07-09 03:03 UTC, rovniipoc commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +    private final CustomLinkedList<Task> historyList = new CustomLinkedList<>();
Вопрос:
Правильно ли я понимаю, что если бы это было не учебное задание, то логичнее было бы использовать LinkedHashSet:
- элементы хранятся в порядке добавления
- нет повторяющихся элементов
- обращение к элементу занимает константное время O(1)
?

2024-07-09 03:36 UTC, rovniipoc commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +    public static class CustomLinkedList<T> {
После внесенных изменений код не проходит CheckStyle (Error:  /home/runner/work/java-kanban/java-kanban/./src/ru/yandex/javacource/brykalov/schedule/manager/Node.java:3:19: Class type name 'Task' must match pattern '(^[A-Z][0-9]?)$|([A-Z][a-zA-Z0-9]*[T]$)'. [ClassTypeParameterName])

2024-07-09 03:41 UTC, rovniipoc commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +    private final CustomLinkedList<Task> historyList = new CustomLinkedList<>();
После внесенных изменений код не проходит CheckStyle
Error:  /home/runner/work/java-kanban/java-kanban/./src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java:41:42: Class type name 'Task' must match pattern '(^[A-Z][0-9]?)$|([A-Z][a-zA-Z0-9]*[T]$)'. [ClassTypeParameterName]

Строка 41:42 выглядит сейчас так:
```
 public static class CustomLinkedList<Task> {
        private Node<Task> head;
```

Не могу понять почему тестам не нравится название класса Task

2024-07-09 03:42 UTC, rovniipoc commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +    public static class CustomLinkedList<T> {
После внесенных изменений код не проходит CheckStyle
Error:  /home/runner/work/java-kanban/java-kanban/./src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java:41:42: Class type name 'Task' must match pattern '(^[A-Z][0-9]?)$|([A-Z][a-zA-Z0-9]*[T]$)'. [ClassTypeParameterName]

Строка 41:42 выглядит сейчас так:
```
 public static class CustomLinkedList<Task> {
        private Node<Task> head;
```

Не могу понять почему тестам не нравится название класса Task

2024-07-09 03:59 UTC, rovniipoc commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +    public static class CustomLinkedList<T> {
Upd: разобрался:) теперь строка выглядит так: `public static class CustomLinkedList {`

2024-07-09 19:18 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryHistoryManager.java
> +    private final CustomLinkedList<Task> historyList = new CustomLinkedList<>();
Скорее LinkedList - в этом же задании прям и был смысл реализовать LinkedList в простейшем варианте

2024-07-09 19:22 UTC, YazykovMikhail approved these changes

2024-07-10 16:24 UTC, merged