Sprint 7 solution in file manager
rovniipoc/java-kanban pull request #2
Opened 2024-07-20 18:05 UTC by rovniipoc

Добрый день.
Представляю на ревью решение ТЗ спринта 7.

2024-07-21 19:20 UTC, YazykovMikhail requested changes

2024-07-21 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +    File file;
private final не забывай

2024-07-21 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +            fw.write("id,type,name,status,description,epicId_or_subtasks\n");
вынести 
"id,type,name,status,description,epicId_or_subtasks" в константу HEADERS
Обрати внимание, в заднии нет столбца epicId_or_subtasks, стоит поправить как в задании

2024-07-21 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +    public static class ManagerSaveException extends Error {
Стоит наследоваться от RuntimeException в таких слусаях, раз не собираешься их обрабатывать
и вынеси в отделдьный класс

2024-07-21 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +    public List<String> allEpicsToString() {
Как сказано в заднии стоит сделать метод 
toString  который будет работать для всех задач
например вот так:
public static String toString(Task task) {
return task.getId() + "," + task.getType() + "," + task.getName() + "," + task.getStatus() + "," + task.getDescription() + "," + (task.getType().equals(TaskType.SUBTASK) ? ((Subtask) task).getEpicId() : "");
}

2024-07-21 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +    public List<String> allEpicsToString() {
Соответсвенно остальные методы будут не нужны

2024-07-21 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +    public void save() {
и используя универсальный метод toString будет выглядеть как то так:
```

	protected void save() {
		try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
			writer.write(HEADERS));
			writer.newLine();

			for (Map.Entry<Integer, Task> entry : tasks.entrySet()) {
				final Task task = entry.getValue();
				writer.write(toString(task));
				writer.newLine();
			}

			for (Map.Entry<Integer, Subtask> entry : subtasks.entrySet()) {
				final Task task = entry.getValue();
				writer.write(toString(task));
				writer.newLine();
			}

			for (Map.Entry<Integer, Epic> entry : epics.entrySet()) {
				final Task task = entry.getValue();
				writer.write(toString(task));
				writer.newLine();
			}

			writer.newLine();
		} catch (IOException e) {
			throw new ManagerSaveException("Can't save to file: " + file.getName(), e);
		}
```
Обратви внимание как стоит делать переносы строк, потому что в каждой операционной системы символ перевода строки разный
Так же лучше использовать буферизацию для экономии ресурсов

2024-07-21 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +    public void loadFromFile(File file) throws IOException {
не прокидывай, выбрасывай свое исключение с каким нибудь сообщением что не удалось загрузить

2024-07-21 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +
Обрати внимание, в заднии говорится метод для парсинга вынести в отдельный метод Task fromString(String value)

2024-07-21 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +                    addNewTask(new Task(name, description, status));
Нелья вызывать метод добавления, ведь будет генерироваться новый идентификатор, который может не совпадать, ведь какие то задчи могли быть удалены, например в середине.
задачи стоит создавать с id и добавлять напрямую в хранилиище, у тебя как раз поля protected

2024-07-21 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +            }
Так же нужно восстанавливать счетчик идентификатора, ведь программа должна продолиться, а не начаться заного

2024-07-21 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +    public void loadFromFile(File file) throws IOException {
СПОЙЛЕР

Можешь подсмотреть какие то мысли, если будет тяжело

```
	public FileBackedTaskManager loadFromFile(File file) {
		final FileBackedTaskManager taskManager = new FileBackedTaskManager(file);
		try {
			final String csv = Files.readString(file.toPath());
			final String[] lines = csv.split(System.lineSeparator());
			int generatorId = 0;
			for (int i = 1; i < lines.length; i++) {
				String line = lines[i];
				if (line.isEmpty()) {
					break;
				}
				final Task task = taskFromString(line);
				final int id = task.getId();
				if (id > generatorId) {
					generatorId = id;
				}
				taskManager.addTask(task);
			}
			for (Map.Entry<Integer, Subtask> e : taskManager.subtasks.entrySet()) {
				final Subtask subtask = e.getValue();
				final Epic epic = taskManager.epics.get(subtask.getEpicId());
				epic.addSubtaskId(subtask.getId());
				taskManager.updateEpic(subtask.getEpicId());
			}
			taskManager.generatorId = generatorId;
		} catch (IOException e) {
			throw new ManagerSaveException("Can't read form file: " + file.getName(), e);
		}
		return taskManager;
	}
```
ТАк же понадобиться метод как раз добавления :

```
	protected void addAnyTask(Task task) {
		final int id = task.getId();
		switch (task.getType()) {
			case TASK:
				tasks.put(id, task);
				break;
			case SUBTASK:
				subtasks.put(id, (Subtask) task);
				break;
			case EPIC:
				epics.put(id, (Epic) task);
				break;
		}
	}
```

2024-07-21 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/save/file.csv
> +id,type,name,status,description,epicId_or_subtasks
Файл должен лежать по пути:
"resources/task.csv"
создай(должна быть) папку в корне resources

2024-07-21 19:20 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/TaskType.java
> +
Добавь поле TaskType taskType в каждую из задач
или еще проще сделай метод для каждой задачи
public TaskType getType() {
return TaskType.TASK;
}
который будет возвращать свой тип соответсвенно
Что бы однозначно идетифицировать задачу и это поле есть в файле

2024-07-22 05:34 UTC, rovniipoc commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +    public void loadFromFile(File file) throws IOException {
Добрый день.
Есть ли смысл делать локальные переменные в методах финальными?

2024-07-22 05:41 UTC, rovniipoc commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +    public void loadFromFile(File file) throws IOException {
Добрый день.
Есть ли смысл делать final локальные переменные Task task, int id как в этом примере?
Это ведь не поля класса, а локальные переменные и после выполнения итерации цикла все равно будут "уничтожены".
Не является ли это "загромождением" кода и "лишней пустой" работой?

2024-07-22 06:02 UTC, rovniipoc commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +    public void loadFromFile(File file) throws IOException {
Я вместо этого подхода:
```
for (Map.Entry<Integer, Subtask> e : taskManager.subtasks.entrySet()) {
				final Subtask subtask = e.getValue();
				final Epic epic = taskManager.epics.get(subtask.getEpicId());
				epic.addSubtaskId(subtask.getId());
				taskManager.updateEpic(subtask.getEpicId());
			}
```
сделал следующее в методе Task taskFromString(String str):
```
case EPIC: {
                Epic epic = new Epic(name, description);
                epic.setStatus(status);
                epic.setSubtaskIds(subtasks);
                return epic;
            }
```
Это не является нарушением?
Ведь если мы считываем файл сохранения и напрямую добавляем его в Map, то почему бы не присвоить ему статус напрямую из файла сохранения?

2024-07-22 15:42 UTC, rovniipoc commented
Что то я запутался в коммитах...

2024-07-22 20:01 UTC, YazykovMikhail approved these changes

2024-07-22 20:01 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +    private static final String HEADERS = "id,type,name,status,description";
Статические переменные обьявляются первыми в классе

В заднии хедеры выглядять вот так:
id,type,name,status,description,epic
похоже у тебя epic потерялся

2024-07-22 20:01 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/FileBackedTaskManager.java
> +    private static final String HEADERS = "id,type,name,status,description";
Ведь если задача Сабтаска, то при сохранении epicId сохраняется и сейчас тоже, но хедера нет

2024-07-23 16:43 UTC, merged