Sprint 8 solution time and duration
rovniipoc/java-kanban pull request #3
Opened 2024-08-05 19:01 UTC by rovniipoc

Михаил, приветствую и представляю на ревью решение ТЗ восьмого спринта.

2024-08-06 15:56 UTC, YazykovMikhail requested changes

2024-08-06 15:56 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryTaskManager.java
> +        return prioritizedTasks.stream().toList();
Честно говоря так попроще:
return new ArrayList<>(prioritizedTasks)

2024-08-06 15:56 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryTaskManager.java
> +        // Я не понимаю зачем менять for-each на stream: кода не становится меньше
Я согласен)
В задании это просто в качестве тренировке, иногда функциональное программирование выгоднее, хотя Java создавалась как простой язык и долго избегала этого подхода
Поэтому я настаивать не буду

2024-08-06 15:56 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryTaskManager.java
> +            return -1;
Нужно выбрасывать свое исключение унаследованное от RuntimeException. Модно пярм туу или  можно в самом методе isOverlap - потому что там можно будет сразу подсветить идентификаторы пересеченных задач, к примеру как то так:
```
			throw new TaskValidationException("Задача пересекаются с id=" + t.getId() + " c " + existStart + " по " + existEnd);
```
только тогда метод isOverlap будет void ну и название нужно будет поменять

2024-08-06 15:56 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryTaskManager.java
> +            return -1;
Это сейчас прогрмма будет завершаться из за исключения, но дальше она будет работать на сервере и исклчение станет сообещние об ошибки а программа будет работать дальше

2024-08-06 15:56 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryTaskManager.java
> +            return -1;
Поправь везде

2024-08-06 15:56 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/manager/InMemoryTaskManager.java
> +
Обьедени вызовы что бы не дублировать код:
```
	protected void updateEpic(int epicId) {
		Epic epic = epics.get(epicId);
		updateEpicStatus(epic);
		updateEpicDuration(epic);
	}
```
и потом вызывай просто один метод там где это нужно

2024-08-06 15:56 UTC, YazykovMikhail commented on src/ru/yandex/javacource/brykalov/schedule/task/Epic.java
Тут стоит добавляется поле 
	private LocalDateTime endTime;
которое будет также высчитываться в методе updateEpicDuration
Потому что оно зависит от его сабтасок

2024-08-07 17:44 UTC, rovniipoc commented on src/ru/yandex/javacource/brykalov/schedule/task/Epic.java
Добрый вечер.
Добавил.
Но ведь мы и так могли в любой момент получить endTime эпика через родительский метод getEndTime() с помощью startTime и duration.
Значения startTime и duration для эпика вычисляются в updateEpicDuration и записываются в эпик (значения вычисляются на основании сабтасок эпика).

2024-08-07 17:47 UTC, rovniipoc commented
И снова здравствуйте :)
Представляю на ревью, доработанный по замечаниям, проект.

2024-08-07 18:32 UTC, YazykovMikhail approved these changes

2024-08-08 19:47 UTC, merged